version: "3"
services:
    api:
        build: .
        ports:
            - "5000:5000"
        depends_on: 
            - mongo
        volumes:
            - "./:/usr/src/app"
    mongo:
        image: "mongo:latest"
        ports: 
            - "27017:27017"
            